- name : variable to print
  hosts : web
  vars:
    NAME : "Hari Prasad"
    EXP : "12"
  tasks:
  - name : print the info
    ansible.builtin.debug:
      msg: "Hi i m {{NAME}} having {{EXP}} years of experience"

