- name : getehring facts
  hosts: web
  become: yes
  tasks:
  - name: print the facts
    ansible.builtin.debug:
      msg: "{{ansible_facts}}"
  - name : install ngnx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
      state: Enabled
    when: ansible_os_family == "RedHat"