- name : loops demo
  hosts: web
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop:
    - Hari
    - Suresh
    - Robert
    - Alek
    - 1234