- name : loops advanced
  hosts: web
  tasks:
  - name: loops advanced
    ansible.builtin.package
    name: "{{item.name}}"
    state: "{{item.state}}"

  loop:
  - {name: 'mysql', state: 'absent'}
  - {name: 'nginx',state: 'present'}
  - {name: 'Python3',state: 'present'}
