- name : demo on filters
  hosts: web
  tasks:
  - name: print the default varables
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible')}}"
  - name : upper and lower
    vars : 
       greeting : "Hello Ansible"
    ansible.builtin.debug:
       msg: "{{greeting | upper }} , {{greeting | lower }}"
  - name: upper
    vars : 
       greet : "hello ansible"
    ansible.builtin.debug:
        msg: "{{greet | upper}}"
  - name : loop
    vars :
       num : [20,7,6,8,9]
    ansible.builtin.debug:
      msg: >-
        {% if item == 'min' %}
        Minimum value is {{ num | min }}
        {% elif item == 'max' %}
        Maximum value is {{ num | max }}
        {% elif item == 'unique' %}
        Unique values are {{ num | unique | join(', ') }}
        {% endif %}
    loop :
    - min
    - max
    - unique
    
