- name : demo on filters
  hosts: web
  tasks:
  - name: print the default varables
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible')}}"
  - name : upper and lower
    vars : 
       greeting : "Hello Ansible"
    ansible.builtin.debug:
       msg: "{{greeting | upper }}"
       msg: "{{greeting | lower }}"
  - name: upper
    vars : 
       greet : "hello ansible"
    ansible.builtin.debug:
        msg: "{{greet | upper}}"
