- name: Install boto3 and botocore for all users
  hosts: web
  become: yes
  tasks:
    - name: Install boto3 and botocore system-wide
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
        state: present
